USE opensensors;

INSERT INTO messages (device_id, date_and_hour, created_at, payload, content_type)
            VALUES   ('79f4572a-5493-486e-9abe-7337ea06ba4b','2014-04-20 07', '2013-04-20 07:01:00','{"value": 1}', 'application/json');

INSERT INTO messages (device_id, date_and_hour, created_at, payload, content_type)
            VALUES   ('79f4572a-5493-486e-9abe-7337ea06ba4b','2014-04-20 07', '2013-04-20 07:02:00','{"value": 2}', 'application/json');

INSERT INTO messages (device_id, date_and_hour, created_at, payload, content_type)
            VALUES   ('79f4572a-5493-486e-9abe-7337ea06ba4b','2014-04-20 07', '2013-04-20 07:03:00','{"value": 3}', 'application/json');
